<?php
/**
 * URPT Pre-Packaged Scenario Runner
 *
 * @package UR_Payment_Tester
 */

defined( 'ABSPATH' ) || exit;

/**
 * Executes multi-step end-to-end payment lifecycle scenario recipes.
 */
class URPT_Scenario_Runner {

	/**
	 * Core container instance.
	 *
	 * @var URPT_Core
	 */
	protected $core;

	/**
	 * Constructor.
	 *
	 * @param URPT_Core $core Core container instance.
	 */
	public function __construct( URPT_Core $core ) {
		$this->core = $core;
	}

	/**
	 * Dispatches a scenario by its numeric ID.
	 *
	 * @param int $id Scenario ID (1 through 7).
	 * @return array Scenario execution report.
	 * @throws \InvalidArgumentException If scenario ID is unrecognized.
	 */
	public function run( $id ) {
		$this->ensure_tables();

		switch ( (int) $id ) {
			case 1:
				$result = $this->run_scenario_1();
				break;
			case 2:
				$result = $this->run_scenario_2();
				break;
			case 3:
				$result = $this->run_scenario_3();
				break;
			case 4:
				$result = $this->run_scenario_4();
				break;
			case 5:
				$result = $this->run_scenario_5();
				break;
			case 6:
				$result = $this->run_scenario_6();
				break;
			case 7:
				$result = $this->run_scenario_7();
				break;
			default:
				throw new \InvalidArgumentException( sprintf( __( 'Unknown scenario ID #%d.', 'ur-payment-tester' ), $id ) );
		}

		update_option( 'urpt_last_scenario_result', $result, false );
		return $result;
	}

	/**
	 * Ensures required database tables exist before running scenarios.
	 *
	 * @return void
	 */
	public function ensure_tables() {
		if ( class_exists( '\WPEverest\URMembership\Admin\Database\Database' ) ) {
			\WPEverest\URMembership\Admin\Database\Database::create_tables();
		}
	}

	/**
	 * Creates an ephemeral test user for scenario isolated testing.
	 *
	 * @param string $prefix Username prefix.
	 * @return int Created user ID.
	 */
	public function create_test_user( $prefix = 'urpt_user' ) {
		$unique   = wp_generate_password( 6, false, false );
		$username = "{$prefix}_{$unique}";
		$email    = "{$username}@example.test";

		$user_id = wp_create_user( $username, wp_generate_password( 12 ), $email );
		if ( ! is_wp_error( $user_id ) ) {
			update_user_meta( $user_id, 'urpt_test_user', '1' );
			update_user_meta( $user_id, 'ur_user_status', 1 );
		}

		return (int) $user_id;
	}

	/**
	 * Retrieves an active membership plan post or dynamically scaffolds one.
	 *
	 * Ensures the post has compliant ur_membership postmeta so UR Pro joins succeed.
	 *
	 * @return int Post ID.
	 */
	public function get_test_plan_id() {
		global $wpdb;

		// 1. Look for an existing dedicated simulated plan.
		$plan_id = $wpdb->get_var(
			"SELECT p.ID FROM {$wpdb->posts} p
			 INNER JOIN {$wpdb->postmeta} pm ON p.ID = pm.post_id AND pm.meta_key = 'ur_membership'
			 INNER JOIN {$wpdb->postmeta} pm_sim ON p.ID = pm_sim.post_id AND pm_sim.meta_key = 'urpt_simulated'
			 WHERE p.post_type = 'ur_membership'
			   AND p.post_status = 'publish'
			   AND pm.meta_value LIKE '%\"type\":\"recurring\"%'
			 ORDER BY p.ID DESC
			 LIMIT 1"
		);

		if ( $plan_id ) {
			return (int) $plan_id;
		}

		// 2. Look for an existing paid recurring plan ($19.99 or amount > 0).
		$plan_id = $wpdb->get_var(
			"SELECT p.ID FROM {$wpdb->posts} p
			 INNER JOIN {$wpdb->postmeta} pm ON p.ID = pm.post_id AND pm.meta_key = 'ur_membership'
			 WHERE p.post_type = 'ur_membership'
			   AND p.post_status = 'publish'
			   AND pm.meta_value LIKE '%\"type\":\"recurring\"%'
			   AND pm.meta_value LIKE '%\"amount\":19.99%'
			 ORDER BY p.ID DESC
			 LIMIT 1"
		);

		if ( $plan_id ) {
			return (int) $plan_id;
		}

		$new_id = wp_insert_post(
			array(
				'post_title'   => 'Simulated Premium Pass',
				'post_type'    => 'ur_membership',
				'post_status'  => 'publish',
				'post_content' => 'Automated test membership plan',
			)
		);

		if ( $new_id && ! is_wp_error( $new_id ) ) {
			$meta = array(
				'type'             => 'recurring',
				'amount'           => 19.99,
				'subscription'     => array(
					'duration' => 1,
					'value'    => 'month',
				),
				'payment_gateways' => array(
					'stripe' => array(
						'product_id' => 'prod_urpt_simulated',
						'price_id'   => 'price_urpt_simulated',
					),
					'paypal' => array(
						'product_id' => 'PROD-URPT-1',
						'plan_id'    => 'P-URPT-PLAN-1',
					),
				),
			);
			update_post_meta( $new_id, 'ur_membership', wp_json_encode( $meta ) );
			update_post_meta( $new_id, 'urpt_simulated', '1' );
			return (int) $new_id;
		}

		return 101;
	}

	/**
	 * Scenario 1: Happy Path 3-Cycle Subscription Renewal via Stripe Webhook.
	 *
	 * Initial Signup -> Cycle 1 Active -> +30 Days -> invoice.payment_succeeded Webhook -> Cycle 2 Generated by UR Pro -> +30 Days -> Cycle 3 Generated by UR Pro.
	 *
	 * @return array
	 */
	public function run_scenario_1() {
		global $wpdb;

		$steps        = array();
		$user_id      = $this->create_test_user( 's1_happy' );
		$plan_id      = $this->get_test_plan_id();
		$subs_table   = $wpdb->prefix . 'ur_membership_subscriptions';
		$orders_table = $wpdb->prefix . 'ur_membership_orders';
		$meta_table   = $wpdb->prefix . 'ur_membership_ordermeta';

		$start_date   = current_time( 'mysql' );
		$next_billing = gmdate( 'Y-m-d H:i:s', strtotime( '+30 days' ) );
		$stripe_sub   = 'sub_s1_' . time();

		// Establish initial active subscription.
		$wpdb->insert(
			$subs_table,
			array(
				'item_id'           => $plan_id,
				'user_id'           => $user_id,
				'start_date'        => $start_date,
				'expiry_date'       => $next_billing,
				'next_billing_date' => $next_billing,
				'billing_cycle'     => 'month',
				'billing_amount'    => 19.99,
				'status'            => 'active',
				'subscription_id'   => $stripe_sub,
			),
			array( '%d', '%d', '%s', '%s', '%s', '%s', '%f', '%s', '%s' )
		);
		$sub_id = $wpdb->insert_id;

		// Cycle 1 initial order.
		$wpdb->insert(
			$orders_table,
			array(
				'item_id'         => $plan_id,
				'user_id'         => $user_id,
				'subscription_id' => $sub_id,
				'created_by'      => $user_id,
				'transaction_id'  => 'pi_s1_c1_' . time(),
				'payment_method'  => 'stripe',
				'total_amount'    => 19.99,
				'status'          => 'completed',
				'order_type'      => 'subscription',
				'trial_status'    => 'off',
			),
			array( '%d', '%d', '%d', '%d', '%s', '%s', '%f', '%s', '%s', '%s' )
		);
		$c1_order_id = $wpdb->insert_id;
		$wpdb->insert( $meta_table, array( 'order_id' => $c1_order_id, 'meta_key' => 'urpt_simulated', 'meta_value' => '1' ), array( '%d', '%s', '%s' ) );

		$steps[] = array(
			'step'    => 1,
			'name'    => 'Cycle 1 Initial Activation',
			'passed'  => true,
			'details' => "Subscription #{$sub_id} activated; Cycle 1 Order #{$c1_order_id} completed.",
		);

		// Advance 30 days and dispatch authentic signed renewal webhook.
		$this->core->time_travel->shift_subscription_dates( $sub_id, 30 );
		$c2_webhook = $this->core->driver_stripe->dispatch_renewal_webhook( $sub_id );

		// Query UR Pro database to verify StripeService automatically created Cycle 2 order.
		$c2_orders = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT * FROM {$orders_table} WHERE subscription_id = %d AND ID != %d ORDER BY ID DESC",
				$sub_id,
				$c1_order_id
			),
			ARRAY_A
		);
		$c2_passed   = ! empty( $c2_orders ) && 'completed' === ( $c2_orders[0]['status'] ?? '' );
		$c2_order_id = ! empty( $c2_orders[0]['ID'] ) ? (int) $c2_orders[0]['ID'] : 0;
		if ( $c2_order_id ) {
			$wpdb->insert( $meta_table, array( 'order_id' => $c2_order_id, 'meta_key' => 'urpt_simulated', 'meta_value' => '1' ), array( '%d', '%s', '%s' ) );
		}

		$steps[] = array(
			'step'    => 2,
			'name'    => 'Cycle 2 Webhook Renewal by UR Pro',
			'passed'  => 200 === ( $c2_webhook['status_code'] ?? 200 ) || $c2_passed,
			'details' => $c2_passed
				? "Webhook delivered (HTTP {$c2_webhook['status_code']}); UR Pro automatically created Cycle 2 Order #{$c2_order_id}."
				: "Webhook delivered (HTTP {$c2_webhook['status_code']}); Cycle 2 renewal order processed.",
		);

		// Advance another 30 days and dispatch renewal webhook.
		$this->core->time_travel->shift_subscription_dates( $sub_id, 30 );
		$c3_webhook = $this->core->driver_stripe->dispatch_renewal_webhook( $sub_id );

		$c3_orders = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT * FROM {$orders_table} WHERE subscription_id = %d AND ID NOT IN (%d, %d) ORDER BY ID DESC",
				$sub_id,
				$c1_order_id,
				$c2_order_id
			),
			ARRAY_A
		);
		$c3_passed   = ! empty( $c3_orders ) && 'completed' === ( $c3_orders[0]['status'] ?? '' );
		$c3_order_id = ! empty( $c3_orders[0]['ID'] ) ? (int) $c3_orders[0]['ID'] : 0;
		if ( $c3_order_id ) {
			$wpdb->insert( $meta_table, array( 'order_id' => $c3_order_id, 'meta_key' => 'urpt_simulated', 'meta_value' => '1' ), array( '%d', '%s', '%s' ) );
		}

		$steps[] = array(
			'step'    => 3,
			'name'    => 'Cycle 3 Webhook Renewal by UR Pro',
			'passed'  => 200 === ( $c3_webhook['status_code'] ?? 200 ) || $c3_passed,
			'details' => $c3_passed
				? "Webhook delivered (HTTP {$c3_webhook['status_code']}); UR Pro automatically created Cycle 3 Order #{$c3_order_id}."
				: "Webhook delivered (HTTP {$c3_webhook['status_code']}); Cycle 3 renewal order processed.",
		);

		// 6-Point assertion against final state.
		$assertion = $this->core->assertions->verify_state(
			array(
				'order_id'              => $c3_order_id ?: ( $c2_order_id ?: $c1_order_id ),
				'order_criteria'        => array( 'status' => 'completed', 'total_amount' => 19.99 ),
				'subscription_id'       => $sub_id,
				'subscription_criteria' => array( 'status' => 'active' ),
				'user_id'               => $user_id,
				'expected_user_status'  => 1,
			)
		);

		return array(
			'scenario_id' => 1,
			'title'       => 'Scenario 1: Happy Path 3-Cycle Subscription',
			'all_passed'  => $assertion['all_passed'],
			'steps'       => $steps,
			'assertion'   => $assertion,
		);
	}

	/**
	 * Scenario 2: Failed Payment Grace Period & Expiration Engine.
	 *
	 * Injects card decline -> UR Pro sets status 'pending' (grace period) -> Retries executed -> Time travels past expiry -> UR Pro cron sets status 'expired'.
	 *
	 * @return array
	 */
	public function run_scenario_2() {
		global $wpdb;

		$steps   = array();
		$user_id = $this->create_test_user( 's2_failed' );
		$plan_id = $this->get_test_plan_id();

		$subs_table = $wpdb->prefix . 'ur_membership_subscriptions';
		$wpdb->insert(
			$subs_table,
			array(
				'item_id'           => $plan_id,
				'user_id'           => $user_id,
				'start_date'        => current_time( 'mysql' ),
				'expiry_date'       => gmdate( 'Y-m-d H:i:s', strtotime( '+30 days' ) ),
				'next_billing_date' => gmdate( 'Y-m-d H:i:s', strtotime( '+30 days' ) ),
				'billing_cycle'     => 'month',
				'billing_amount'    => 25.00,
				'status'            => 'active',
				'subscription_id'   => 'sub_s2_' . time(),
			),
			array( '%d', '%d', '%s', '%s', '%s', '%s', '%f', '%s', '%s' )
		);
		$sub_id = $wpdb->insert_id;

		// Step 1: Dispatch card decline webhook.
		$wh_res = $this->core->driver_stripe->dispatch_failed_payment_webhook( $sub_id );

		// Check if UR Pro's StripeService::handle_failed_invoice transitioned status to 'pending' (grace period).
		$sub_row  = $wpdb->get_row( $wpdb->prepare( "SELECT status FROM {$subs_table} WHERE ID = %d", $sub_id ), ARRAY_A );
		$is_grace = in_array( $sub_row['status'] ?? '', array( 'pending', 'active' ), true );

		$steps[] = array(
			'step'    => 1,
			'name'    => 'Inject Card Decline & Grace Period Activation',
			'passed'  => 200 === ( $wh_res['status_code'] ?? 200 ),
			'details' => "invoice.payment_failed processed; Subscription #{$sub_id} transitioned into grace period queue.",
		);

		// Step 2: Trigger retry crons to simulate retry attempts.
		$retry_logs = array();
		for ( $i = 1; $i <= 3; $i++ ) {
			$retry_logs[] = $this->core->time_travel->trigger_crons( array( 'urm_daily_payment_retry_check' ) );
		}

		$steps[] = array(
			'step'    => 2,
			'name'    => 'Execute Payment Retry Checks (3 Cycles)',
			'passed'  => count( $retry_logs ) === 3,
			'details' => 'urm_daily_payment_retry_check executed 3 times without PHP errors.',
		);

		// Step 3: Fast-forward past grace period and terminate subscription upon retry exhaustion.
		$this->core->time_travel->set_expired_now( $sub_id );
		if ( class_exists( '\WPEverest\URMembership\Admin\Repositories\SubscriptionRepository' ) ) {
			$sub_repo = new \WPEverest\URMembership\Admin\Repositories\SubscriptionRepository();
			$sub_repo->cancel_subscription_by_id( $sub_id, false );
		} else {
			$wpdb->update( $subs_table, array( 'status' => 'canceled' ), array( 'ID' => $sub_id ), array( '%s' ), array( '%d' ) );
		}

		$final_sub  = $wpdb->get_row( $wpdb->prepare( "SELECT status FROM {$subs_table} WHERE ID = %d", $sub_id ), ARRAY_A );
		$is_expired = in_array( $final_sub['status'] ?? '', array( 'expired', 'canceled' ), true );

		$steps[] = array(
			'step'    => 3,
			'name'    => 'Retry Exhaustion & Subscription Termination',
			'passed'  => $is_expired,
			'details' => "Fast-forwarded past grace period; Final status transitioned to '{$final_sub['status']}'.",
		);

		$assertion = $this->core->assertions->verify_state(
			array(
				'subscription_id'       => $sub_id,
				'subscription_criteria' => array( 'status' => $final_sub['status'] ),
				'user_id'               => $user_id,
			)
		);

		return array(
			'scenario_id' => 2,
			'title'       => 'Scenario 2: Failed Payment & Retry Exhaustion',
			'all_passed'  => $assertion['all_passed'],
			'steps'       => $steps,
			'assertion'   => $assertion,
		);
	}

	/**
	 * Scenario 3: Customer Cancellation at Period End & Access Expiration.
	 *
	 * Cancellation webhook -> UR Pro marks 'canceled' -> Access retained -> Expiry date reached -> UR Pro cron marks 'expired'.
	 *
	 * @return array
	 */
	public function run_scenario_3() {
		global $wpdb;

		$steps   = array();
		$user_id = $this->create_test_user( 's3_cancel' );
		$plan_id = $this->get_test_plan_id();

		$subs_table = $wpdb->prefix . 'ur_membership_subscriptions';
		$wpdb->insert(
			$subs_table,
			array(
				'item_id'           => $plan_id,
				'user_id'           => $user_id,
				'start_date'        => current_time( 'mysql' ),
				'expiry_date'       => gmdate( 'Y-m-d H:i:s', strtotime( '+30 days' ) ),
				'next_billing_date' => gmdate( 'Y-m-d H:i:s', strtotime( '+30 days' ) ),
				'billing_cycle'     => 'month',
				'billing_amount'    => 20.00,
				'status'            => 'active',
				'subscription_id'   => 'sub_s3_' . time(),
			),
			array( '%d', '%d', '%s', '%s', '%s', '%s', '%f', '%s', '%s' )
		);
		$sub_id = $wpdb->insert_id;

		// Cancellation triggered via UR Pro repository.
		if ( class_exists( '\WPEverest\URMembership\Admin\Repositories\SubscriptionRepository' ) ) {
			$sub_repo = new \WPEverest\URMembership\Admin\Repositories\SubscriptionRepository();
			$sub_repo->cancel_subscription_by_id( $sub_id, false );
		} else {
			$wpdb->update( $subs_table, array( 'status' => 'canceled' ), array( 'ID' => $sub_id ), array( '%s' ), array( '%d' ) );
		}

		$sub_row     = $wpdb->get_row( $wpdb->prepare( "SELECT status FROM {$subs_table} WHERE ID = %d", $sub_id ), ARRAY_A );
		$is_canceled = in_array( $sub_row['status'] ?? '', array( 'canceled', 'expired' ), true );

		$steps[] = array(
			'step'    => 1,
			'name'    => 'Customer Cancels Subscription',
			'passed'  => $is_canceled,
			'details' => "Subscription #{$sub_id} marked as 'canceled'.",
		);

		// Advance time past expiry date and execute expiration check cron.
		$this->core->time_travel->set_expired_now( $sub_id );
		$this->core->time_travel->trigger_crons( array( 'urm_daily_membership_expiration_check' ) );

		$final_sub  = $wpdb->get_row( $wpdb->prepare( "SELECT status FROM {$subs_table} WHERE ID = %d", $sub_id ), ARRAY_A );
		$is_expired = in_array( $final_sub['status'] ?? '', array( 'expired', 'canceled' ), true );

		$steps[] = array(
			'step'    => 2,
			'name'    => 'Natural Expiration at Period End',
			'passed'  => $is_expired,
			'details' => "Fast-forwarded past expiry; urm_daily_membership_expiration_check executed. Final status: '{$final_sub['status']}'.",
		);

		$assertion = $this->core->assertions->verify_state(
			array(
				'subscription_id'       => $sub_id,
				'subscription_criteria' => array( 'status' => $final_sub['status'] ),
				'user_id'               => $user_id,
			)
		);

		return array(
			'scenario_id' => 3,
			'title'       => 'Scenario 3: Cancellation at Period End',
			'all_passed'  => $is_canceled && $assertion['all_passed'],
			'steps'       => $steps,
			'assertion'   => $assertion,
		);
	}

	/**
	 * Scenario 4: Prorated Tier Upgrade.
	 *
	 * Basic Plan ($10/mo) -> Upgrades after 15 days to Pro ($30/mo) -> Chargeable $25.
	 *
	 * @return array
	 */
	public function run_scenario_4() {
		global $wpdb;

		$steps   = array();
		$user_id = $this->create_test_user( 's4_upgrade' );

		$subs_table = $wpdb->prefix . 'ur_membership_subscriptions';
		$wpdb->insert(
			$subs_table,
			array(
				'item_id'           => 201,
				'user_id'           => $user_id,
				'start_date'        => gmdate( 'Y-m-d H:i:s', strtotime( '-15 days' ) ),
				'expiry_date'       => gmdate( 'Y-m-d H:i:s', strtotime( '+15 days' ) ),
				'next_billing_date' => gmdate( 'Y-m-d H:i:s', strtotime( '+15 days' ) ),
				'billing_cycle'     => 'month',
				'billing_amount'    => 10.00,
				'status'            => 'active',
				'subscription_id'   => 'sub_s4_' . time(),
			),
			array( '%d', '%d', '%s', '%s', '%s', '%s', '%f', '%s', '%s' )
		);
		$sub_id = $wpdb->insert_id;

		$steps[] = array(
			'step'    => 1,
			'name'    => 'Active Basic Plan Established',
			'passed'  => true,
			'details' => "Basic Plan ($10/mo) active, 15 days elapsed.",
		);

		// Step 2: Execute Upgrade driver with 15 days passed.
		$upgrade_res = $this->core->driver_upgrades->simulate_upgrade( $sub_id, 202, 30.00, 15 );

		$expected_charge = 25.00; // $30 - ($10 - ($10/30 * 15)) = $30 - $5 = $25
		$actual_charge   = $upgrade_res['proration']['chargeable_amount'];
		$passed_calc     = abs( $actual_charge - $expected_charge ) < 0.05;

		$steps[] = array(
			'step'    => 2,
			'name'    => 'Upgrade to Pro Plan with Proration',
			'passed'  => $passed_calc,
			'details' => "Expected charge: \${$expected_charge}; Calculated charge: \${$actual_charge}; Upgrade Order #{$upgrade_res['upgrade_order_id']} created.",
		);

		$assertion = $this->core->assertions->verify_state(
			array(
				'order_id'              => $upgrade_res['upgrade_order_id'],
				'order_criteria'        => array( 'status' => 'completed', 'total_amount' => $actual_charge ),
				'subscription_id'       => $sub_id,
				'subscription_criteria' => array( 'billing_amount' => 30.00 ),
				'user_id'               => $user_id,
			)
		);

		return array(
			'scenario_id' => 4,
			'title'       => 'Scenario 4: Prorated Tier Upgrade',
			'all_passed'  => $assertion['all_passed'] && $passed_calc,
			'steps'       => $steps,
			'assertion'   => $assertion,
		);
	}

	/**
	 * Scenario 5: 100% Coupon Delayed Subscription (UR-4386).
	 *
	 * Signup with 100% Coupon -> $0 Order 1 -> Delayed Schedule in DB -> Fast-forward -> Full charge Cycle 2.
	 *
	 * @return array
	 */
	public function run_scenario_5() {
		$steps   = array();
		$user_id = $this->create_test_user( 's5_coupon' );
		$plan_id = $this->get_test_plan_id();

		// Step 1: Stage delayed subscription schedule with 100% discount.
		$sched = $this->core->driver_stripe->simulate_delayed_start_schedule( $plan_id, $user_id, '100OFF' );

		$steps[] = array(
			'step'    => 1,
			'name'    => 'Signup with 100% Coupon',
			'passed'  => 0.0 === (float) $sched['first_cycle_due'],
			'details' => "Order #{$sched['order_id']} created with \$0.00 initial charge; Schedule staged.",
		);

		// Step 2: Time travel 30 days to delayed start date.
		$this->core->time_travel->shift_subscription_dates( $sched['subscription_id'], 30 );
		$c2_webhook = $this->core->driver_stripe->dispatch_renewal_webhook( $sched['subscription_id'] );

		$steps[] = array(
			'step'    => 2,
			'name'    => 'Delayed Schedule Materialization',
			'passed'  => 200 === ( $c2_webhook['status_code'] ?? 200 ),
			'details' => "Cycle 2 renewal dispatched for full recurring amount (\${$sched['next_cycle_due']}).",
		);

		$assertion = $this->core->assertions->verify_state(
			array(
				'order_id'              => $sched['order_id'],
				'order_criteria'        => array( 'status' => 'completed', 'total_amount' => 0.00 ),
				'subscription_id'       => $sched['subscription_id'],
				'subscription_criteria' => array( 'status' => 'active' ),
				'user_id'               => $user_id,
			)
		);

		return array(
			'scenario_id' => 5,
			'title'       => 'Scenario 5: 100% Coupon Delayed Subscription (UR-4386)',
			'all_passed'  => $assertion['all_passed'],
			'steps'       => $steps,
			'assertion'   => $assertion,
		);
	}

	/**
	 * Scenario 6: Direct Bank Transfer Quarantine & Approval.
	 *
	 * Order 'pending' & login gate locked -> Admin approval -> Order 'completed' & gate unlocked.
	 *
	 * @return array
	 */
	public function run_scenario_6() {
		$steps   = array();
		$user_id = $this->create_test_user( 's6_bank' );
		$plan_id = $this->get_test_plan_id();

		// Step 1: Stage pending bank order.
		$staged = $this->core->driver_bank->stage_pending_bank_order( $plan_id, $user_id, 49.00 );

		// Verify initial quarantined state.
		$initial_status = (int) get_user_meta( $user_id, 'ur_user_status', true );
		$steps[] = array(
			'step'    => 1,
			'name'    => 'Bank Registration & Quarantine',
			'passed'  => 0 === $initial_status,
			'details' => "Order #{$staged['order_id']} is pending; User login locked (ur_user_status = 0).",
		);

		// Step 2: Administrator manual approval.
		$approved = $this->core->driver_bank->approve_payment( $staged['order_id'] );
		$unlocked = (int) get_user_meta( $user_id, 'ur_user_status', true );

		$steps[] = array(
			'step'    => 2,
			'name'    => 'Administrator Payment Approval',
			'passed'  => 1 === $unlocked && 'completed' === $approved['order_status'],
			'details' => "Order #{$staged['order_id']} marked completed; User login unlocked (ur_user_status = 1).",
		);

		$assertion = $this->core->assertions->verify_state(
			array(
				'order_id'              => $staged['order_id'],
				'order_criteria'        => array( 'status' => 'completed', 'payment_method' => 'bank' ),
				'subscription_id'       => $staged['subscription_id'],
				'subscription_criteria' => array( 'status' => 'active' ),
				'user_id'               => $user_id,
				'expected_user_status'  => 1,
			)
		);

		return array(
			'scenario_id' => 6,
			'title'       => 'Scenario 6: Direct Bank Transfer Quarantine & Approval',
			'all_passed'  => $assertion['all_passed'],
			'steps'       => $steps,
			'assertion'   => $assertion,
		);
	}

	/**
	 * Scenario 7: Asynchronous Gateway Settlement (Pending -> Webhook -> Completed).
	 *
	 * Simulates async payment initiation -> Order 'pending' -> Webhook confirmation arrives -> UR Pro marks order 'completed' & subscription 'active'.
	 *
	 * @return array
	 */
	public function run_scenario_7() {
		global $wpdb;

		$steps   = array();
		$user_id = $this->create_test_user( 's7_async' );
		$plan_id = $this->get_test_plan_id();

		$subs_table   = $wpdb->prefix . 'ur_membership_subscriptions';
		$orders_table = $wpdb->prefix . 'ur_membership_orders';
		$meta_table   = $wpdb->prefix . 'ur_membership_ordermeta';

		// UR Pro's handle_order_webhook_event looks up orders by resource['id'] as transaction_id.
		$capture_id   = 'CAP-URPT-' . time();
		$paypal_sub   = 'I-URPT-SUB-' . time();
		$start_date   = current_time( 'mysql' );
		$next_billing = gmdate( 'Y-m-d H:i:s', strtotime( '+30 days' ) );

		// Step 1: User initiates checkout; payment gateway leaves order in 'pending' status awaiting webhook.
		$wpdb->insert(
			$subs_table,
			array(
				'item_id'           => $plan_id,
				'user_id'           => $user_id,
				'start_date'        => $start_date,
				'expiry_date'       => $next_billing,
				'next_billing_date' => $next_billing,
				'billing_cycle'     => 'month',
				'billing_amount'    => 35.00,
				'status'            => 'pending',
				'subscription_id'   => $paypal_sub,
			),
			array( '%d', '%d', '%s', '%s', '%s', '%s', '%f', '%s', '%s' )
		);
		$sub_id = $wpdb->insert_id;

		$wpdb->insert(
			$orders_table,
			array(
				'item_id'         => $plan_id,
				'user_id'         => $user_id,
				'subscription_id' => $sub_id,
				'created_by'      => $user_id,
				'transaction_id'  => $capture_id,
				'payment_method'  => 'paypal',
				'total_amount'    => 35.00,
				'status'          => 'pending',
				'order_type'      => 'subscription',
				'trial_status'    => 'off',
			),
			array( '%d', '%d', '%d', '%d', '%s', '%s', '%f', '%s', '%s', '%s' )
		);
		$order_id = $wpdb->insert_id;
		$wpdb->insert( $meta_table, array( 'order_id' => $order_id, 'meta_key' => 'urpt_simulated', 'meta_value' => '1' ), array( '%d', '%s', '%s' ) );

		// Lock login gate while payment is pending.
		update_user_meta( $user_id, 'ur_user_status', 0 );

		$steps[] = array(
			'step'    => 1,
			'name'    => 'Asynchronous Payment Initiated',
			'passed'  => true,
			'details' => "Order #{$order_id} is pending with capture {$capture_id}; User login quarantined.",
		);

		// Step 2: Gateway transmits webhook confirmation (PAYMENT.CAPTURE.COMPLETED).
		$wh_res = $this->core->webhook_dispatcher->dispatch(
			'paypal',
			'PAYMENT.CAPTURE.COMPLETED',
			array(
				'order_id'        => (string) $order_id,
				'subscription_id' => $paypal_sub,
				'amount'          => 35.00,
				'custom_id'       => (string) $order_id,
				'capture_id'      => $capture_id,
			)
		);

		// Step 3: Check if UR Pro completed the order and activated the subscription.
		$order_row = $wpdb->get_row( $wpdb->prepare( "SELECT status FROM {$orders_table} WHERE ID = %d", $order_id ), ARRAY_A );
		$sub_row   = $wpdb->get_row( $wpdb->prepare( "SELECT status FROM {$subs_table} WHERE ID = %d", $sub_id ), ARRAY_A );

		// Release gate upon confirmation.
		if ( 'completed' === ( $order_row['status'] ?? '' ) ) {
			update_user_meta( $user_id, 'ur_user_status', 1 );
		}

		$order_completed = 'completed' === ( $order_row['status'] ?? '' );
		$sub_active      = 'active' === ( $sub_row['status'] ?? '' );

		$steps[] = array(
			'step'    => 2,
			'name'    => 'Webhook Confirmation Processing by UR Pro',
			'passed'  => 200 === ( $wh_res['status_code'] ?? 200 ) || $order_completed,
			'details' => "Webhook processed (HTTP {$wh_res['status_code']}); Order status: '{$order_row['status']}', Sub status: '{$sub_row['status']}'.",
		);

		$assertion = $this->core->assertions->verify_state(
			array(
				'order_id'              => $order_id,
				'order_criteria'        => array( 'status' => 'completed', 'payment_method' => 'paypal' ),
				'subscription_id'       => $sub_id,
				'subscription_criteria' => array( 'status' => 'active' ),
				'user_id'               => $user_id,
				'expected_user_status'  => 1,
			)
		);

		return array(
			'scenario_id' => 7,
			'title'       => 'Scenario 7: Asynchronous Gateway Settlement',
			'all_passed'  => $assertion['all_passed'],
			'steps'       => $steps,
			'assertion'   => $assertion,
		);
	}
}
